### ISSUE TITLE
Comp for case studies

### ISSUE THREAD

**Issue by cweber** [sunlightlabs/mpt#4]
This will include 3 full case studies (not featured in the book), short descriptions of the remaining 9 case studies (possible videos?), a link to the 20 page report (decision on formatting later)

**Comment by cweber** [comment]
Do we need to include who the researcher was or any other details like that?

**Comment by heyitsolivia** [comment]
Question—what happens when the case study description copy are uneven lengths—like with longer or shorter copy? do we have control over copy?

Icons/illustrations for the book and pdf callout are looking pretty sweet by the way :cake:

**Comment by cweber** [comment]
Yeah, if I had more time I'd throw some variety into the mix. I will suggest a character count, but the odds of us hitting that exactly for all of them is low.

Will likely be treated like the first section of the resources page.
http://moneypoliticstransparency.org/resources

**Comment by cweber** [comment]
Adding a bit of description lorem in around the book and pdf callouts

**Comment by cweber** [comment]
![mpt_casestudies_redux](https://cloud.githubusercontent.com/assets/417657/7504192/531dab48-f416-11e4-8208-94460428c9a8.jpg)
